
spring:
    h2:
        console:
            enabled : true
            path : /h2
    datasource:
        url : jdbc:h2:file:~/test
        username : test
        password : test123
        driver-class-name : org.h2.Driver
